// gpu-worker.js — the WebGPU backend. One of these replaces the whole pool of
// sim-worker.js instances when the Compute toggle is on GPU, and it speaks
// exactly the same message protocol ('init', 'config', 'track', 'pop',
// 'reset', 'run', 'export', 'import'), so engine.js treats it as a pool of
// one and nothing above the engine knows the difference.
//
// WHAT RUNS WHERE, AND WHY
// Each simulation step is strictly sequential for a car — sensors feed the
// network, the network drives the physics, the physics decides the next
// sensors — so moving any single piece (the neural network, say) to the GPU
// on its own would need a CPU<->GPU round trip every step, and a round trip
// costs far more than the ~65 multiply-adds the network actually is. The only
// split that pays is the whole step: walls, raycasts, network, physics,
// gates, laps and fitness all run in the compute shader below, the population
// stays resident in GPU memory for the whole generation, and the only traffic
// is one small uniform write per chunk going in and one readback of the car
// state coming out (≈128 bytes a car). Evolution stays on the CPU — it runs
// once a generation, needs every car's fitness, and that readback is already
// happening anyway. Track geometry is still generated by sim.c (this worker
// hosts a wasm instance for exactly that, and for building the start-of-run
// car state), then uploaded once per track.
//
// LOCKSTEP. A generation ends the moment any car completes the target lap
// count, at a step boundary, for every car at once. So each step is its own
// dispatch — consecutive dispatches in a WebGPU pass are ordered, which is
// the one global barrier a GPU offers — and a car that finishes its laps
// records the frame it happened on (stopFrame), which every car checks
// before it steps. Cars that would run past that frame don't. Hyper mode's
// big chunks are submitted in sub-batches with a tiny pipelined probe of that
// flag, so once the generation is over the rest of the chunk isn't even
// submitted.
//
// PARALLELISM. A small population (a phone's 150 cars) is nowhere near
// enough threads to keep a GPU busy, and each car's wall scan is the long
// pole of a step. So up to eight threads share one car: they split that car's
// wall bucket between them, each keeps its own seven ray minima and collision
// flag, and one of them combines the eight results through workgroup memory
// and does the (short) rest of the step. How many threads per car is picked
// from the population size (see lanesFor) so there are always roughly two
// thousand in flight; the result is bit-identical whichever is picked, since
// min() and "any hit" don't depend on order.
//
// NUMERICS. WGSL has no f64 and its built-in sin/cos/atan2 are only
// guaranteed to a few thousandths on [-pi, pi] — and a car's heading is never
// wrapped, so it drifts far outside that. The trig below is therefore done by
// hand in f32 (Cody-Waite reduction + minimax polynomials, ~1 ulp), and the
// network's tanh is the exact same f32 routine sim.c uses. The result tracks
// the CPU build to within f32 rounding, not bit for bit — tools/gpuparity.mjs
// is what holds it to that.

const WG = 64;
const STATE_WORDS = 32;
const CAR_BYTES = STATE_WORDS * 4;
const MAX_GATES = 256;
const AUX_WORDS = 4 + MAX_GATES * 2;
const AUX_BYTES = AUX_WORDS * 4;
const INT_MAX = 0x7fffffff;
// Steps per submitted sub-batch in a long (hyper mode) chunk, and how many of
// those may be queued before waiting on the oldest one's probe. Big enough
// that the GPU never runs dry waiting on a map, small enough that a
// generation ending early wastes at most a couple of hundred empty steps.
const SUB_STEPS = 128;
const PROBE_DEPTH = 2;
// Wall-clock cap on one round. A hyper-mode chunk asks for thousands of
// steps, which a fast GPU clears in tens of milliseconds but a weak one (or a
// software adapter) could spend seconds on — with the main loop waiting on it
// and nothing on screen updating. Past the budget the round stops submitting
// and reports exactly how far it got; that is the same answer sim.c's run()
// would give for a smaller `iters`, and the engine simply asks again.
const ROUND_BUDGET_MS = 100;

const WGSL = /* wgsl */`
override LANES: u32 = 1u;
override CPW: u32 = 64u / LANES;

const IN_N: i32 = 11;
const MAX_GATES: i32 = 256;
const HW: f32 = 7.0;
const HH: f32 = 3.5;
const STOPPED_SPEED: f32 = 0.05;
const STOPPED_GRACE_FRAMES: i32 = 15;
const PROGRESS_WINDOW_FRAMES: i32 = 180;
const TURN_GRIP_REF_SPEED: f32 = 3.0;
const CAR_LAT_GRIP: f32 = 0.93;
const FOCUS_BOOST: f32 = 3.0;
const PI_F: f32 = 3.14159265358979323846;
const C30: f32 = 0.86602540378443864676;
const S30: f32 = 0.5;

struct Params {
  maxSpeed: f32, accel: f32, turnSpeed: f32, brakeStrength: f32,
  sensorLen: f32, trackLen: f32, wMax: f32, gridCell: f32,
  gridOx: f32, gridOy: f32, fpad0: f32, fpad1: f32,
  initialTTL: i32, targetLaps: i32, cpN: i32, startCp: i32,
  zoneN: i32, centerN: i32, gridNx: i32, gridNy: i32,
  focusLo: i32, focusHi: i32, popN: i32, hidden: i32,
  stride: i32, cpOff: i32, zoneOff: i32, ctrOff: i32,
  wOff: i32, gsOff: i32, giOff: i32, hasGrid: i32,
  hasBuckets: i32, tiOff: i32, brOff: i32, ipad0: i32,
}

// Same fields, same order as pack_state() in sim.c.
struct Car {
  x: f32, y: f32, angle: f32, vx: f32, vy: f32, speed: f32, fitness: f32,
  crashed: i32, ttl: i32, frames: i32, nextCP: i32, laps: i32, cpReached: i32,
  lastLap: f32, prevLapFrame: i32, lastCpFrame: i32, roadSeg: i32, focused: i32,
  out0: f32, out1: f32,
  inp: array<f32, 11>,
  spare: f32,
}

struct Aux {
  stopFrame: atomic<i32>,
  alive: atomic<i32>,
  apad0: i32,
  apad1: i32,
  crash: array<atomic<i32>, 256>,
  gate: array<f32, 256>,
}

// Four storage buffers, not six: WebGPU's compatibility mode (what older
// Android phones get, on OpenGL ES) allows only four per shader stage, and
// packing the read-only tables together costs nothing here.
@group(0) @binding(0) var<uniform> P: Params;
// Wall buckets, two vec4s a wall: (x1, y1, dx, dy) and (mx, my, r2, halfLen).
@group(0) @binding(1) var<storage, read> walls: array<vec4<f32>>;
// Everything else read-only, one after another: gates (6 floats each), zones
// (5), centreline (2 per sample) and half-widths from 0; bucket starts and
// the road grid as bit-cast i32s from P.tiOff; the brains from P.brOff.
@group(0) @binding(2) var<storage, read> td: array<f32>;
@group(0) @binding(3) var<storage, read_write> cars: array<Car>;
@group(0) @binding(4) var<storage, read_write> aux: Aux;

fn ti(i: i32) -> i32 { return bitcast<i32>(td[P.tiOff + i]); }

var<workgroup> red: array<f32, 512>;

// sin and cos of an unbounded heading: Cody-Waite reduction by pi/2 in three
// parts (the first two carry few enough bits that n * part is exact), then
// the Cephes single-precision minimax polynomials on |r| <= pi/4.
fn sincos(x: f32) -> vec2<f32> {
  let n = round(x * 0.63661977236758134308);
  let r = ((x - n * 1.5703125) - n * 4.837512969970703125e-4) - n * 7.54978995489188216e-8;
  let z = r * r;
  let s = ((-1.9515295891e-4 * z + 8.3321608736e-3) * z - 1.6666654611e-1) * z * r + r;
  let c = ((2.443315711809948e-5 * z - 1.388731625493765e-3) * z + 4.166664568298827e-2) * z * z - 0.5 * z + 1.0;
  let k = i32(n) & 3;
  if (k == 0) { return vec2<f32>(s, c); }
  if (k == 1) { return vec2<f32>(c, -s); }
  if (k == 2) { return vec2<f32>(-s, -c); }
  return vec2<f32>(-c, s);
}

fn atanPoly(x: f32) -> f32 {
  let ax = abs(x);
  var y0 = 0.0;
  var t = ax;
  if (ax > 2.414213562373095) { y0 = 1.5707963267948966; t = -1.0 / ax; }
  else if (ax > 0.4142135623730950) { y0 = 0.78539816339744831; t = (ax - 1.0) / (ax + 1.0); }
  let z = t * t;
  let y = y0 + ((((8.05374449538e-2 * z - 1.38776856032e-1) * z + 1.99777106478e-1) * z - 3.33329491539e-1) * z * t + t);
  return select(y, -y, x < 0.0);
}

fn atan2f(y: f32, x: f32) -> f32 {
  if (y == 0.0) {
    let xNeg = x < 0.0 || (x == 0.0 && (bitcast<u32>(x) >> 31u) != 0u);
    if (!xNeg) { return 0.0; }
    return select(PI_F, -PI_F, (bitcast<u32>(y) >> 31u) != 0u);
  }
  if (x == 0.0) { return select(-PI_F * 0.5, PI_F * 0.5, y > 0.0); }
  let a = atanPoly(y / x);
  if (x > 0.0) { return a; }
  return select(a - PI_F, a + PI_F, y > 0.0);
}

// sim.c's nn_tanh, line for line: 2^x by writing the exponent field, a
// degree-7 polynomial for the fraction, clamped where f32 saturates anyway.
fn nnTanh(x: f32) -> f32 {
  if (x > 9.011) { return 1.0; }
  if (x < -9.011) { return -1.0; }
  let y = x * 2.885390081777926814;
  let n = round(y);
  let f = y - n;
  var p = 1.5252733804059840e-5;
  p = p * f + 1.5403530393381609e-4;
  p = p * f + 1.3333558146428443e-3;
  p = p * f + 9.6181291076284772e-3;
  p = p * f + 5.5504108664821580e-2;
  p = p * f + 2.4022650695910071e-1;
  p = p * f + 6.9314718055994531e-1;
  p = p * f + 1.0;
  let e = p * bitcast<f32>((i32(n) + 127) << 23u);
  return (e - 1.0) / (e + 1.0);
}

fn inFocus(g: i32) -> bool {
  if (P.focusLo < 0) { return false; }
  if (P.focusLo <= P.focusHi) { return g >= P.focusLo && g <= P.focusHi; }
  return g >= P.focusLo || g <= P.focusHi;
}

fn pointSegDist2(px: f32, py: f32, ax: f32, ay: f32, bx: f32, by: f32) -> f32 {
  let dx = bx - ax;
  let dy = by - ay;
  let l2 = dx * dx + dy * dy;
  var t = 0.0;
  if (l2 > 0.0) { t = ((px - ax) * dx + (py - ay) * dy) / l2; }
  t = select(select(t, 1.0, t > 1.0), 0.0, t < 0.0);
  let ex = px - (ax + t * dx);
  let ey = py - (ay + t * dy);
  return ex * ex + ey * ey;
}

fn segClaims(i: i32, px: f32, py: f32) -> bool {
  var j = i + 1;
  if (j >= P.centerN) { j = 0; }
  let a = P.ctrOff + 2 * i;
  let b = P.ctrOff + 2 * j;
  let r = max(td[P.wOff + i], td[P.wOff + j]);
  return pointSegDist2(px, py, td[a], td[a + 1], td[b], td[b + 1]) < r * r;
}

// sim.c's insideRoad. Returns (inside, new hint); the hint only changes when
// some segment is found to claim the point, exactly as there.
fn insideRoad(px: f32, py: f32, hint: i32) -> vec2<i32> {
  if (P.hasGrid == 0) { return vec2<i32>(1, hint); }
  let n = P.centerN;
  if (hint >= 0 && hint < n) {
    for (var d = -2; d <= 2; d++) {
      var i = hint + d;
      if (i < 0) { i += n; } else if (i >= n) { i -= n; }
      if (segClaims(i, px, py)) { return vec2<i32>(1, i); }
    }
  }
  let gx = i32(floor((px - P.gridOx) / P.gridCell));
  let gy = i32(floor((py - P.gridOy) / P.gridCell));
  let xlo = max(gx - 1, 0);
  let xhi = min(gx + 1, P.gridNx - 1);
  let ylo = max(gy - 1, 0);
  let yhi = min(gy + 1, P.gridNy - 1);
  for (var ix = xlo; ix <= xhi; ix++) {
    for (var iy = ylo; iy <= yhi; iy++) {
      let k = iy * P.gridNx + ix;
      let s1 = ti(P.gsOff + k + 1);
      for (var s = ti(P.gsOff + k); s < s1; s++) {
        let seg = ti(P.giOff + s);
        if (segClaims(seg, px, py)) { return vec2<i32>(1, seg); }
      }
    }
  }
  return vec2<i32>(0, hint);
}

// Does segment a->b cross the wall starting at (x1, y1) with extent (wdx, wdy)?
// sim.c's division-free, sign-normalised test.
fn segCross(ax: f32, ay: f32, bx: f32, by: f32, x1: f32, y1: f32, wdx: f32, wdy: f32) -> bool {
  let abx = bx - ax;
  let aby = by - ay;
  var bottom = wdy * abx - wdx * aby;
  if (bottom == 0.0) { return false; }
  let acx = ax - x1;
  let acy = ay - y1;
  var tn = wdx * acy - wdy * acx;
  var un = acy * abx - acx * aby;
  if (bottom < 0.0) { bottom = -bottom; tn = -tn; un = -un; }
  return tn >= 0.0 && tn <= bottom && un >= 0.0 && un <= bottom;
}

// Everything in updateCar before the wall tests. 1 = the car's step is over
// (it crashed), 2 = go on to the walls. Deterministic, so every lane sharing
// a car runs it and arrives at the same car.
fn prePhase(c: ptr<function, Car>, trig: ptr<function, vec2<f32>>, prev: ptr<function, vec2<f32>>) -> u32 {
  (*c).ttl -= 1;
  (*c).frames += 1;
  if ((*c).ttl <= 0) { (*c).crashed = 1; return 1u; }
  let steer = (*c).out0;
  let throttle = (*c).out1;
  if ((*c).speed > STOPPED_SPEED) {
    let authority = min(TURN_GRIP_REF_SPEED / (*c).speed, 1.0);
    (*c).angle += steer * P.turnSpeed * authority;
  }
  let sc = sincos((*c).angle);
  *trig = sc;
  let sA = sc.x;
  let cA = sc.y;
  var vx = (*c).vx;
  var vy = (*c).vy;
  if (throttle > 0.0) {
    vx += cA * throttle * P.accel;
    vy += sA * throttle * P.accel;
  } else if (throttle < 0.0) {
    let sp = sqrt(vx * vx + vy * vy);
    if (sp > 1.0e-4) {
      let dec = min(-throttle * P.brakeStrength, sp);
      let k = (sp - dec) / sp;
      vx *= k;
      vy *= k;
    }
  }
  let latVel = vx * (-sA) + vy * cA;
  var grip = CAR_LAT_GRIP;
  if (abs(latVel) > 2.5) { grip *= 0.8; }
  vx += (-sA) * -latVel * grip;
  vy += cA * -latVel * grip;
  vx *= 0.99;
  vy *= 0.99;
  var speed = sqrt(vx * vx + vy * vy);
  if (speed > P.maxSpeed) { let r = P.maxSpeed / speed; vx *= r; vy *= r; speed = P.maxSpeed; }
  (*c).vx = vx;
  (*c).vy = vy;
  (*c).speed = speed;
  if ((*c).frames > STOPPED_GRACE_FRAMES && speed < STOPPED_SPEED) {
    (*c).crashed = 1; (*c).fitness -= 50.0; return 1u;
  }
  *prev = vec2<f32>((*c).x, (*c).y);
  (*c).x += vx;
  (*c).y += vy;
  if ((*c).frames - (*c).lastCpFrame < PROGRESS_WINDOW_FRAMES && speed > STOPPED_SPEED) {
    let mult = select(1.0, FOCUS_BOOST, (*c).focused != 0 && inFocus((*c).nextCP));
    (*c).fitness += 0.1 * mult;
  }
  let x = (*c).x;
  let y = (*c).y;
  if (x < -100.0 || x > 1300.0 || y < -100.0 || y > 1000.0) { (*c).crashed = 1; return 1u; }
  if (P.cpN <= 0 || P.hasBuckets == 0) { (*c).crashed = 1; return 1u; }
  let road = insideRoad(x, y, (*c).roadSeg);
  (*c).roadSeg = road.y;
  if (road.x == 0) { (*c).crashed = 1; (*c).fitness -= 50.0; return 1u; }
  return 2u;
}

// This lane's share of the car's wall bucket: every LANES-th wall, starting
// at the lane's own offset. The seven ray minima and the collision flag are
// both order-independent, so the lanes can be combined in any order.
fn wallPass(c: Car, trig: vec2<f32>, prev: vec2<f32>, lane: u32,
            best: ptr<function, array<f32, 7>>, hit: ptr<function, bool>) {
  let cx = c.x;
  let cy = c.y;
  let sA = trig.x;
  let cA = trig.y;
  let seg = select(0, c.nextCP, c.nextCP >= 0 && c.nextCP < P.cpN);
  let wStart = ti(seg);
  let wEnd = ti(seg + 1);
  let collR = c.speed + 8.0;
  let x0 = cx + cA * HW - sA * HH; let y0 = cy + sA * HW + cA * HH;
  let x1 = cx + cA * HW + sA * HH; let y1 = cy + sA * HW - cA * HH;
  let x2 = cx - cA * HW + sA * HH; let y2 = cy - sA * HW - cA * HH;
  let x3 = cx - cA * HW - sA * HH; let y3 = cy - sA * HW + cA * HH;
  let p = sA * C30;
  let q = cA * S30;
  let r = cA * C30;
  let t = sA * S30;
  let L = P.sensorLen;
  let rc = array<f32, 7>(sA, q + p, r + t, cA, r - t, q - p, -sA);
  let rs = array<f32, 7>(-cA, t - r, p - q, sA, p + q, t + r, cA);
  var abx: array<f32, 7>;
  var aby: array<f32, 7>;
  for (var k = 0; k < 7; k++) {
    abx[k] = (cx + rc[k] * L) - cx;
    aby[k] = (cy + rs[k] * L) - cy;
  }
  for (var w = wStart + i32(lane); w < wEnd; w += i32(LANES)) {
    let A = walls[2 * w];
    let B = walls[2 * w + 1];
    let ddx = cx - B.x;
    let ddy = cy - B.y;
    let d2 = ddx * ddx + ddy * ddy;
    if (!(d2 <= B.z)) { continue; }
    let hl = B.w;
    if (ddx * cA + ddy * sA <= hl) {
      let acx = cx - A.x;
      let acy = cy - A.y;
      let tn0 = A.z * acy - A.w * acx;
      for (var k = 0; k < 7; k++) {
        var bottom = A.w * abx[k] - A.z * aby[k];
        var tn = tn0;
        var un = acy * abx[k] - acx * aby[k];
        if (bottom < 0.0) { bottom = -bottom; tn = -tn; un = -un; }
        if (bottom != 0.0 && tn >= 0.0 && tn <= bottom && un >= 0.0 && un <= bottom) {
          (*best)[k] = min((*best)[k], tn / bottom);
        }
      }
    }
    let cr = collR + hl;
    if (d2 <= cr * cr) {
      if (segCross(prev.x, prev.y, cx, cy, A.x, A.y, A.z, A.w) ||
          segCross(x0, y0, x1, y1, A.x, A.y, A.z, A.w) ||
          segCross(x1, y1, x2, y2, A.x, A.y, A.z, A.w) ||
          segCross(x2, y2, x3, y3, A.x, A.y, A.z, A.w) ||
          segCross(x3, y3, x0, y0, A.x, A.y, A.z, A.w)) {
        *hit = true;
        return;
      }
    }
  }
}

fn feedForward(c: ptr<function, Car>, ci: i32) {
  let h = P.hidden;
  let base = P.brOff + ci * P.stride;
  let offHO = base + IN_N * h;
  let offBH = offHO + 2 * h;
  let offBO = offBH + h;
  var hid: array<f32, 16>;
  for (var k = 0; k < h; k++) {
    var acc = td[offBH + k];
    for (var j = 0; j < IN_N; j++) { acc += (*c).inp[j] * td[base + j * h + k]; }
    hid[k] = nnTanh(acc);
  }
  var s0 = td[offBO];
  var s1 = td[offBO + 1];
  for (var j = 0; j < h; j++) {
    s0 += hid[j] * td[offHO + 2 * j];
    s1 += hid[j] * td[offHO + 2 * j + 1];
  }
  (*c).out0 = nnTanh(s0);
  (*c).out1 = nnTanh(s1);
}

// Everything in updateCar after the wall tests: the crash they found, zones,
// gates and laps, then the sensor readings and the network.
fn tailPhase(c: ptr<function, Car>, ci: i32, trig: vec2<f32>, prev: vec2<f32>, best: array<f32, 7>, hit: bool) {
  if (hit) { (*c).crashed = 1; (*c).fitness -= 50.0; return; }
  let cx = (*c).x;
  let cy = (*c).y;
  let speed = (*c).speed;
  var fitMult = 1.0;
  for (var z = 0; z < P.zoneN; z++) {
    let o = P.zoneOff + 5 * z;
    let dx = cx - td[o];
    let dy = cy - td[o + 1];
    let zr = td[o + 2];
    if (dx * dx + dy * dy < zr * zr) {
      let ty = i32(td[o + 3]);
      if (ty == 0 && speed > P.maxSpeed * 0.7) { (*c).fitness += 2.0; }
      else if (ty == 1) { (*c).fitness += 2.0; }
      else if (ty == 2) { fitMult = 3.0; }
      else if (ty == 3) {
        if ((*c).frames >= i32(td[o + 4])) { (*c).crashed = 1; return; }
      }
    }
  }

  let nxt = (*c).nextCP;
  let hasRel = nxt >= 0 && nxt < P.cpN;
  var gi = nxt;
  var more = hasRel;
  for (var pp = 0; pp < 8 && more; pp++) {
    let o = P.cpOff + 6 * gi;
    let p1x = td[o]; let p1y = td[o + 1]; let p2x = td[o + 2]; let p2y = td[o + 3];
    let dx = cx - td[o + 4];
    let dy = cy - td[o + 5];
    if (pp == 0 && dx * dx + dy * dy > 160000.0) { (*c).crashed = 1; return; }
    let mx = (p1x + p2x) * 0.5;
    let my = (p1y + p2y) * 0.5;
    let cdx = cx - mx;
    let cdy = cy - my;
    let gateR = P.wMax + speed + 8.0;
    if (cdx * cdx + cdy * cdy >= gateR * gateR) { break; }
    if (!(segCross(prev.x, prev.y, cx, cy, p1x, p1y, p2x - p1x, p2y - p1y) || (cdx * cdx + cdy * cdy < 400.0))) { break; }
    (*c).cpReached += 1;
    (*c).nextCP = ((*c).nextCP + 1) % P.cpN;
    (*c).ttl = P.initialTTL;
    let meanGap = P.trackLen / f32(max(P.cpN, 1));
    let idealCp = meanGap / max(P.maxSpeed, 0.001);
    let dtCp = f32((*c).frames - (*c).lastCpFrame);
    (*c).lastCpFrame = (*c).frames;
    let gAbs = ((*c).nextCP - 1 + P.cpN) % P.cpN;
    if (ci == 0 && gAbs >= 0 && gAbs < MAX_GATES) { aux.gate[gAbs] = idealCp / max(dtCp, idealCp); }
    let gateMult = select(1.0, FOCUS_BOOST, (*c).focused != 0 && inFocus(gAbs));
    (*c).fitness += 500.0 * (1.0 + 3.0 * (idealCp / max(dtCp, idealCp))) * fitMult * gateMult;
    if ((*c).nextCP == (P.startCp + 1) % P.cpN && P.cpN > 2) {
      (*c).laps += 1;
      let lapFrames = f32((*c).frames - (*c).prevLapFrame);
      (*c).lastLap = lapFrames / 60.0;
      (*c).prevLapFrame = (*c).frames;
      let idealLap = P.trackLen / max(P.maxSpeed, 0.001);
      (*c).fitness += 3000.0 * (1.0 + 3.0 * (idealLap / max(lapFrames, idealLap))) * fitMult;
    }
    gi = (*c).nextCP;
  }

  for (var k = 0; k < 7; k++) { (*c).inp[k] = 1.0 - best[k]; }
  if (hasRel) {
    let o = P.cpOff + 6 * nxt;
    let tX = (td[o] + td[o + 2]) * 0.5;
    let tY = (td[o + 1] + td[o + 3]) * 0.5;
    var relAng = atan2f(tY - cy, tX - cx) - (*c).angle;
    if (relAng > PI_F || relAng < -PI_F) {
      let turns = floor((relAng + PI_F) * 0.15915494309189533577);
      relAng = (relAng - turns * 6.28125) - turns * 1.9353071795864769253e-3;
    }
    (*c).inp[7] = speed / P.maxSpeed;
    (*c).inp[8] = relAng / PI_F;
  } else {
    (*c).inp[7] = 0.0;
    (*c).inp[8] = 0.0;
  }
  (*c).inp[9] = (*c).out0;
  (*c).inp[10] = (*c).out1;
  feedForward(c, ci);
}

@compute @workgroup_size(64)
fn step(@builtin(local_invocation_index) lid: u32, @builtin(workgroup_id) wid: vec3<u32>) {
  let lane = lid % LANES;
  let ci = wid.x * CPW + lid / LANES;
  var c: Car;
  var phase = 0u;
  var trig = vec2<f32>(0.0, 1.0);
  var prev = vec2<f32>(0.0, 0.0);
  if (ci < u32(P.popN)) {
    c = cars[ci];
    // stopFrame is the frame some car finished the target lap count on; no
    // car steps past it, which is the CPU build's "break after the step
    // where maxLaps reached the target", for every car at once.
    if (c.crashed == 0 && c.frames < atomicLoad(&aux.stopFrame)) {
      phase = prePhase(&c, &trig, &prev);
    }
  }
  var best = array<f32, 7>(1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0);
  var hit = false;
  if (phase == 2u) { wallPass(c, trig, prev, lane, &best, &hit); }

  let o = lid * 8u;
  for (var k = 0u; k < 7u; k++) { red[o + k] = best[k]; }
  red[o + 7u] = select(0.0, 1.0, hit);
  workgroupBarrier();

  if (lane == 0u && phase != 0u) {
    if (phase == 2u) {
      for (var l = 1u; l < LANES; l++) {
        let q = (lid + l) * 8u;
        for (var k = 0u; k < 7u; k++) { best[k] = min(best[k], red[q + k]); }
        hit = hit || red[q + 7u] != 0.0;
      }
      tailPhase(&c, i32(ci), trig, prev, best, hit);
    }
    cars[ci] = c;
    if (c.crashed != 0) {
      if (c.nextCP >= 0 && c.nextCP < MAX_GATES) { atomicAdd(&aux.crash[c.nextCP], 1); }
      atomicSub(&aux.alive, 1);
    }
    if (c.laps >= P.targetLaps) { atomicMin(&aux.stopFrame, c.frames); }
  }
}
`;

// ---------------------------------------------------------------------------
// Host side.
// ---------------------------------------------------------------------------
let ex = null, memory = null, index = -1;
let device = null, lost = false;
let adapterLabel = '';
const pipes = new Map();          // threads-per-car -> GPUComputePipeline
let bindLayout = null, bindGroup = null, bindDirty = true;
const bufs = { params: null, walls: null, td: null, cars: null, aux: null };
// The current track's read-only tables (floats, then bit-cast ints) — kept
// host-side because the brains share their buffer and a new population, or a
// new track, rewrites the whole thing.
let trackTD = new Float32Array(4), trackTiOff = 0;
let stateStaging = null, auxStaging = null;
const probePool = [];

let popN = 0, popStart = 0, hidden = 5, stride = 0, lanes = 1;
let focusLo = -1, focusHi = -1;
let mirror = new Uint32Array(0);  // the population as of the last readback
let crashMirror = new Int32Array(MAX_GATES);
let gateMirror = new Float32Array(MAX_GATES).fill(-1);

const params = new ArrayBuffer(144);
const pf = new Float32Array(params), pi = new Int32Array(params);
const cfg = { maxSpeed: 10, accel: 0.05, turnSpeed: 0.02, brakeStrength: 0.05, initialTTL: 750, targetLaps: 3 };
const trk = { cpN: 0, startCp: 0, zoneN: 0, centerN: 0, gridNx: 0, gridNy: 0, hasGrid: 0, hasBuckets: 0,
              gridCell: 1, gridOx: 0, gridOy: 0, trackLen: 0, wMax: 0, zoneOff: 0, ctrOff: 0, wOff: 0, gsOff: 0, giOff: 0 };

const f32v = (ptr, len) => new Float32Array(memory.buffer, ptr, len);
const i32v = (ptr, len) => new Int32Array(memory.buffer, ptr, len);

// Threads per car: enough that roughly two thousand are in flight whatever
// the population, never more than eight (a bucket rarely has enough walls to
// share further) — see PARALLELISM above.
function lanesFor(n) {
    let l = 1;
    while (l < 8 && n * l * 2 <= 2048) l *= 2;
    return l;
}

function writeParams() {
    pf[0] = cfg.maxSpeed; pf[1] = cfg.accel; pf[2] = cfg.turnSpeed; pf[3] = cfg.brakeStrength;
    pf[4] = ex ? ex.sensor_len() : 180; pf[5] = trk.trackLen; pf[6] = trk.wMax; pf[7] = trk.gridCell;
    pf[8] = trk.gridOx; pf[9] = trk.gridOy; pf[10] = 0; pf[11] = 0;
    pi[12] = cfg.initialTTL; pi[13] = cfg.targetLaps; pi[14] = trk.cpN; pi[15] = trk.startCp;
    pi[16] = trk.zoneN; pi[17] = trk.centerN; pi[18] = trk.gridNx; pi[19] = trk.gridNy;
    pi[20] = focusLo; pi[21] = focusHi; pi[22] = popN; pi[23] = hidden;
    pi[24] = stride; pi[25] = 0; pi[26] = trk.zoneOff; pi[27] = trk.ctrOff;
    pi[28] = trk.wOff; pi[29] = trk.gsOff; pi[30] = trk.giOff; pi[31] = trk.hasGrid;
    pi[32] = trk.hasBuckets; pi[33] = trackTiOff; pi[34] = trackTD.length; pi[35] = 0;
    device.queue.writeBuffer(bufs.params, 0, params);
}

// Grow-only: a buffer is replaced only when it is too small, so a
// generation-to-generation run at the same population size never allocates.
function ensure(name, bytes, usage) {
    const need = Math.max(16, Math.ceil(bytes / 16) * 16);
    if (bufs[name] && bufs[name].size >= need) return bufs[name];
    if (bufs[name]) bufs[name].destroy();
    bufs[name] = device.createBuffer({ size: need, usage });
    bindDirty = true;
    return bufs[name];
}
function ensureStaging(bytes) {
    const need = Math.max(16, Math.ceil(bytes / 16) * 16);
    if (stateStaging && stateStaging.size >= need) return;
    if (stateStaging) stateStaging.destroy();
    stateStaging = device.createBuffer({ size: need, usage: GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST });
}

// Guarded: on a browser without WebGPU the constant doesn't exist, and this
// file still has to load far enough to report that back as a 'gpu-error'.
const STORAGE_IN = typeof GPUBufferUsage !== 'undefined' ? GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST : 0;

async function initGPU() {
    if (typeof navigator === 'undefined' || !navigator.gpu) throw new Error('WebGPU is not available in this browser');
    // A full ("core") adapter if there is one; otherwise compatibility mode,
    // which is how a GPU without Vulkan/Metal/D3D12 (an older Android phone
    // on OpenGL ES) exposes compute at all. Browsers that don't know the
    // featureLevel option just ignore it.
    let adapter = await navigator.gpu.requestAdapter({ powerPreference: 'high-performance' });
    if (!adapter) adapter = await navigator.gpu.requestAdapter({ powerPreference: 'high-performance', featureLevel: 'compatibility' });
    if (!adapter) throw new Error('no WebGPU adapter — the GPU may be blocklisted or disabled');
    const info = adapter.info || {};
    adapterLabel = [info.vendor, info.architecture].filter(Boolean).join(' ') || 'WebGPU';
    // A software adapter runs the shader on the CPU, slower than the wasm
    // path it would replace; allowed, but labelled so nobody is misled.
    if (info.isFallbackAdapter || adapter.isFallbackAdapter) adapterLabel += ' (software)';
    device = await adapter.requestDevice();
    device.lost.then(li => {
        lost = true;
        if (li.reason !== 'destroyed') self.postMessage({ type: 'gpu-lost', index, message: li.message || 'GPU device lost' });
    });

    const module = device.createShaderModule({ code: WGSL });
    const ci = await module.getCompilationInfo();
    const errs = ci.messages.filter(m => m.type === 'error');
    if (errs.length) throw new Error('shader: ' + errs.map(m => `${m.lineNum}:${m.linePos} ${m.message}`).join('; '));

    const storage = (binding, type) => ({ binding, visibility: GPUShaderStage.COMPUTE, buffer: { type } });
    bindLayout = device.createBindGroupLayout({ entries: [
        { binding: 0, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'uniform' } },
        storage(1, 'read-only-storage'), storage(2, 'read-only-storage'),
        storage(3, 'storage'), storage(4, 'storage')
    ] });
    const layout = device.createPipelineLayout({ bindGroupLayouts: [bindLayout] });
    // All four variants up front, in parallel, while the CPU pool is still
    // the one running — so changing population size later never stalls on a
    // shader compile.
    await Promise.all([1, 2, 4, 8].map(async l => {
        pipes.set(l, await device.createComputePipelineAsync({
            layout, compute: { module, entryPoint: 'step', constants: { LANES: l } }
        }));
    }));

    bufs.params = device.createBuffer({ size: 144, usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST });
    bufs.aux = device.createBuffer({ size: AUX_BYTES, usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST | GPUBufferUsage.COPY_SRC });
    auxStaging = device.createBuffer({ size: AUX_BYTES, usage: GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST });
    for (const n of ['walls', 'td']) ensure(n, 16, GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST);
    ensure('cars', CAR_BYTES, GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST | GPUBufferUsage.COPY_SRC);
    ensureStaging(CAR_BYTES);
    resetAux(0, null);
    writeParams();
}

function rebuildBindGroup() {
    bindGroup = device.createBindGroup({ layout: bindLayout, entries: [
        { binding: 0, resource: { buffer: bufs.params } },
        { binding: 1, resource: { buffer: bufs.walls } },
        { binding: 2, resource: { buffer: bufs.td } },
        { binding: 3, resource: { buffer: bufs.cars } },
        { binding: 4, resource: { buffer: bufs.aux } }
    ] });
    bindDirty = false;
}

function resetAux(alive, gate) {
    const a = new Int32Array(AUX_WORDS);
    a[0] = INT_MAX; a[1] = alive;
    const g = new Float32Array(a.buffer, (4 + MAX_GATES) * 4, MAX_GATES);
    if (gate) g.set(gate); else g.fill(-1);
    device.queue.writeBuffer(bufs.aux, 0, a);
    crashMirror = new Int32Array(MAX_GATES);
    gateMirror = g.slice();
}

function applyConfig(args) {
    ex.set_config(...args);
    cfg.maxSpeed = args[0]; cfg.accel = args[1]; cfg.turnSpeed = args[2]; cfg.brakeStrength = args[3];
    cfg.initialTTL = args[4] | 0; cfg.targetLaps = args[5] | 0;
}

// The track is generated by sim.c, exactly as a CPU worker does it, then
// every array the step reads is flattened into three GPU buffers.
function buildAndUploadTrack(d) {
    const nPts = Math.min(d.path.length, ex.max_path_pts());
    const pIn = f32v(ex.path_in_ptr(), Math.max(1, nPts * 4));
    for (let i = 0; i < nPts; i++) {
        const p = d.path[i];
        pIn[i * 4] = p.x; pIn[i * 4 + 1] = p.y;
        pIn[i * 4 + 2] = p.type === 'corner' ? 1 : 0;
        pIn[i * 4 + 3] = p.radius !== undefined ? p.radius : 60;
    }
    const zones = d.zones || [];
    const nz = Math.min(zones.length, ex.max_zones());
    const zIn = f32v(ex.zone_in_ptr(), Math.max(1, nz * 5));
    const ZID = { speed: 0, precision: 1, focus: 2, spawnkill: 3 };
    for (let i = 0; i < nz; i++) {
        const z = zones[i];
        zIn[i * 5] = z.x; zIn[i * 5 + 1] = z.y; zIn[i * 5 + 2] = z.radius;
        zIn[i * 5 + 3] = ZID[z.type] !== undefined ? ZID[z.type] : -1;
        zIn[i * 5 + 4] = z.killTimer !== undefined ? z.killTimer : 150;
    }
    const hasStart = d.startPos ? 1 : 0;
    const hasAngle = (d.startAngle !== undefined && d.startAngle !== null) ? 1 : 0;
    ex.track_build(ex.path_in_ptr(), nPts, d.width,
        hasStart, hasStart ? d.startPos.x : 0, hasStart ? d.startPos.y : 0,
        hasAngle, hasAngle ? d.startAngle : 0, ex.zone_in_ptr(), nz,
        d.autoWidth ? 1 : 0, d.autoWidthBlend || 0);

    // Views only after the build: it can grow memory, which detaches them.
    const tp = ex.track_info();
    const t = new Uint32Array(memory.buffer, tp, 32), tfl = new Float32Array(memory.buffer, tp, 32);
    trk.cpN = t[0] | 0; trk.startCp = t[1] | 0; trk.zoneN = t[2] | 0; trk.centerN = t[3] | 0;
    trk.gridNx = t[4] | 0; trk.gridNy = t[5] | 0; trk.hasGrid = t[8] | 0; trk.hasBuckets = t[9] | 0;
    trk.gridCell = tfl[25]; trk.gridOx = tfl[26]; trk.gridOy = tfl[27]; trk.trackLen = tfl[28]; trk.wMax = tfl[29];
    const nGridItems = trk.hasGrid ? t[6] : 0, nWalls = trk.hasBuckets ? t[7] : 0;

    const walls = new Float32Array(Math.max(8, nWalls * 8));
    if (nWalls) {
        const cols = [11, 12, 13, 14, 15, 16, 17, 18].map(k => f32v(t[k], nWalls));
        for (let w = 0; w < nWalls; w++) for (let j = 0; j < 8; j++) walls[w * 8 + j] = cols[j][w];
    }

    trk.zoneOff = trk.cpN * 6;
    trk.ctrOff = trk.zoneOff + trk.zoneN * 5;
    trk.wOff = trk.ctrOff + trk.centerN * 2;
    const tfArr = new Float32Array(Math.max(4, trk.wOff + trk.centerN));
    if (trk.cpN > 0) {
        const cps = f32v(t[19], trk.cpN * 7);   // 6 floats + an int apex flag each
        for (let i = 0; i < trk.cpN; i++) for (let j = 0; j < 6; j++) tfArr[i * 6 + j] = cps[i * 7 + j];
    }
    if (trk.zoneN > 0) {
        const zf = f32v(t[20], trk.zoneN * 5), zi = i32v(t[20], trk.zoneN * 5);
        for (let i = 0; i < trk.zoneN; i++) {
            const o = trk.zoneOff + i * 5;
            tfArr[o] = zf[i * 5]; tfArr[o + 1] = zf[i * 5 + 1]; tfArr[o + 2] = zf[i * 5 + 2];
            tfArr[o + 3] = zi[i * 5 + 3]; tfArr[o + 4] = zf[i * 5 + 4];
        }
    }
    if (trk.centerN > 0) {
        tfArr.set(f32v(t[21], trk.centerN * 2), trk.ctrOff);
        if (t[22]) tfArr.set(f32v(t[22], trk.centerN), trk.wOff);
    }

    const nB = trk.hasBuckets ? trk.cpN + 1 : 2;
    const nCells = trk.hasGrid ? trk.gridNx * trk.gridNy + 1 : 0;
    trk.gsOff = nB; trk.giOff = nB + nCells;
    const tiArr = new Int32Array(Math.max(4, trk.giOff + nGridItems));
    if (trk.hasBuckets) tiArr.set(i32v(t[10], trk.cpN + 1), 0);
    if (trk.hasGrid) {
        tiArr.set(i32v(t[23], nCells), trk.gsOff);
        if (nGridItems) tiArr.set(i32v(t[24], nGridItems), trk.giOff);
    }

    device.queue.writeBuffer(ensure('walls', walls.byteLength, STORAGE_IN), 0, walls);
    trackTiOff = tfArr.length;
    trackTD = new Float32Array(tfArr.length + tiArr.length);
    trackTD.set(tfArr, 0);
    new Int32Array(trackTD.buffer).set(tiArr, trackTiOff);
    uploadTD();
    writeParams();
}

// Track tables then brains, in the one read-only buffer the shader reads both
// from. The brains' offset follows the track's size, so either changing means
// writing both.
function uploadTD() {
    const nBrains = popN * stride;
    const buf = ensure('td', (trackTD.length + nBrains) * 4, STORAGE_IN);
    device.queue.writeBuffer(buf, 0, trackTD);
    if (nBrains) device.queue.writeBuffer(buf, trackTD.length * 4, lastBrains, 0, nBrains);
}

// `forceLanes` is for tools/gpuparity.mjs only: it pins threads-per-car so
// the test can prove every split lands on the same bits.
function uploadPopulation(brainsF32, stateU32, alive, gate, forceLanes) {
    stride = ex.brain_stride();
    lastBrains = brainsF32;
    uploadTD();
    const cars = ensure('cars', popN * CAR_BYTES, GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST | GPUBufferUsage.COPY_SRC);
    if (popN) device.queue.writeBuffer(cars, 0, stateU32, 0, popN * STATE_WORDS);
    ensureStaging(popN * CAR_BYTES);
    mirror = stateU32.slice(0, popN * STATE_WORDS);
    lanes = forceLanes || lanesFor(popN);
    resetAux(alive, gate);
    writeParams();
}

// The start-of-run state comes from sim.c's own pop_reset, so a car spawns
// identically on either backend.
function packFromWasm() {
    ex.pack_state();
    return new Uint32Array(memory.buffer, ex.state_ptr(), popN * STATE_WORDS).slice();
}

function aliveIn(state) {
    const s = new Int32Array(state.buffer, state.byteOffset, state.length);
    let n = 0;
    for (let c = 0; c < popN; c++) if (s[c * STATE_WORDS + 7] === 0) n++;
    return n;
}

async function mapRead(buf, bytes) {
    await buf.mapAsync(GPUMapMode.READ, 0, bytes);
    const out = buf.getMappedRange(0, bytes).slice(0);
    buf.unmap();
    return out;
}

async function simulate(iters, budgetMs) {
    if (bindDirty) rebuildBindGroup();
    const deadline = performance.now() + budgetMs;
    let executed = 0;
    const pipe = pipes.get(lanes);
    const nWG = Math.ceil(popN / (WG / lanes));
    device.queue.writeBuffer(bufs.aux, 0, new Int32Array([INT_MAX]));
    let remaining = iters, stopped = false;
    const inflight = [];
    while (remaining > 0 && !stopped) {
        const n = Math.min(SUB_STEPS, remaining);
        remaining -= n;
        executed += n;
        const enc = device.createCommandEncoder();
        const pass = enc.beginComputePass();
        pass.setPipeline(pipe);
        pass.setBindGroup(0, bindGroup);
        for (let s = 0; s < n; s++) pass.dispatchWorkgroups(nWG);
        pass.end();
        let probe = null;
        if (remaining > 0) {
            probe = probePool.pop() || device.createBuffer({ size: 16, usage: GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST });
            enc.copyBufferToBuffer(bufs.aux, 0, probe, 0, 16);
        }
        device.queue.submit([enc.finish()]);
        if (probe) inflight.push({ buf: probe, done: probe.mapAsync(GPUMapMode.READ) });
        if (inflight.length >= PROBE_DEPTH) {
            const p = inflight.shift();
            await p.done;
            const v = new Int32Array(p.buf.getMappedRange(0, 8));
            stopped = v[0] !== INT_MAX || v[1] <= 0 || performance.now() > deadline;
            p.buf.unmap();
            probePool.push(p.buf);
        }
    }
    const bytes = popN * CAR_BYTES;
    const enc = device.createCommandEncoder();
    enc.copyBufferToBuffer(bufs.cars, 0, stateStaging, 0, bytes);
    enc.copyBufferToBuffer(bufs.aux, 0, auxStaging, 0, AUX_BYTES);
    device.queue.submit([enc.finish()]);
    const [stateBuf, auxBuf] = await Promise.all([mapRead(stateStaging, bytes), mapRead(auxStaging, AUX_BYTES)]);
    for (const p of inflight) { await p.done; p.buf.unmap(); probePool.push(p.buf); }
    const a = new Int32Array(auxBuf);
    crashMirror = a.slice(4, 4 + MAX_GATES);
    gateMirror = new Float32Array(auxBuf, (4 + MAX_GATES) * 4, MAX_GATES).slice();
    return { state: new Uint32Array(stateBuf), stopFrame: a[0], executed };
}

// One 'run' round: step, then answer in exactly the shape sim-worker.js
// does, down to the CPU build's rules for maxLaps, allCrashed and the step
// count, so engine.js and the evolve trigger can't tell the two apart.
async function run(msg) {
    const t0 = performance.now();
    const iters = msg.iters | 0;
    const before = new Int32Array(mirror.buffer, mirror.byteOffset, mirror.length);
    let aliveStart = 0, f0 = 0;
    for (let c = 0; c < popN; c++) if (before[c * STATE_WORDS + 7] === 0) { aliveStart++; f0 = before[c * STATE_WORDS + 9]; }

    let after = before, stopFrame = INT_MAX, executed = 0;
    if (aliveStart > 0 && iters > 0 && !lost) {
        try {
            // budgetMs is for tools/gpuparity.mjs, which wants whole chunks.
            const r = await simulate(iters, msg.budgetMs || ROUND_BUDGET_MS);
            mirror = r.state;
            after = new Int32Array(mirror.buffer, mirror.byteOffset, mirror.length);
            stopFrame = r.stopFrame;
            executed = r.executed;
        } catch (e) {
            // Device lost mid-chunk (driver reset, tab backgrounded on some
            // mobile GPUs). No progress this round; the engine is told
            // separately and moves the population back to the CPU from the
            // last good state.
            if (!lost) { lost = true; self.postMessage({ type: 'gpu-lost', index, message: String(e && e.message || e) }); }
        }
    }

    const af = new Float32Array(mirror.buffer, mirror.byteOffset, mirror.length);
    let steps = 0, maxLaps = 0, alive = 0, lastCrash = 0;
    for (let c = 0; c < popN; c++) {
        const o = c * STATE_WORDS;
        if (after[o + 7] === 0) alive++;
        if (before[o + 7] !== 0) continue;
        steps += after[o + 9] - before[o + 9];
        if (after[o + 11] > maxLaps) maxLaps = after[o + 11];
        if (after[o + 9] > lastCrash) lastCrash = after[o + 9];
    }
    // As sim.c's run(executed): all-crashed only if some step began with no
    // car left to move — not when the last one went on the final step.
    const allCrashed = iters <= 0 || aliveStart === 0 ||
        (alive === 0 && stopFrame === INT_MAX && lastCrash < f0 + executed);

    let buffer;
    const stride5 = 5;
    if (msg.wantRender) {
        const len = popN * 18;
        buffer = msg.recycle && msg.recycle.byteLength === len * 4 ? new Float32Array(msg.recycle) : new Float32Array(len);
        for (let c = 0; c < popN; c++) {
            const o = c * STATE_WORDS, r = c * 18;
            buffer[r] = popStart + c; buffer[r + 1] = after[o + 7] ? 1 : 0;
            buffer[r + 2] = af[o]; buffer[r + 3] = af[o + 1]; buffer[r + 4] = af[o + 2]; buffer[r + 5] = af[o + 5];
            buffer[r + 6] = af[o + 18]; buffer[r + 7] = af[o + 19];
            buffer[r + 8] = after[o + 11]; buffer[r + 9] = af[o + 6]; buffer[r + 10] = af[o + 13];
            for (let k = 0; k < 7; k++) buffer[r + 11 + k] = af[o + 20 + k];
        }
    } else {
        const len = popN * stride5;
        buffer = msg.recycle && msg.recycle.byteLength === len * 4 ? new Float32Array(msg.recycle) : new Float32Array(len);
        for (let c = 0; c < popN; c++) {
            const o = c * STATE_WORDS, r = c * stride5;
            buffer[r] = af[o + 6]; buffer[r + 1] = after[o + 11]; buffer[r + 2] = af[o + 13];
            buffer[r + 3] = after[o + 12]; buffer[r + 4] = after[o + 15];
        }
    }
    const crashCount = crashMirror.slice();
    const gateRatio = popStart === 0 ? gateMirror.slice() : null;
    const transfer = [buffer.buffer, crashCount.buffer];
    if (gateRatio) transfer.push(gateRatio.buffer);
    self.postMessage({
        type: 'done', index, start: popStart, count: popN,
        maxLaps, allCrashed, alive, busyMs: performance.now() - t0, carSteps: steps, crashCount,
        render: !!msg.wantRender, stride: stride5, buffer, gateRatio
    }, transfer);
}

async function handle(msg) {
    switch (msg.type) {
        case 'init': {
            index = msg.index;
            const instance = await WebAssembly.instantiate(msg.module, {});
            ex = instance.exports;
            memory = ex.memory;
            try {
                await initGPU();
            } catch (e) {
                self.postMessage({ type: 'gpu-error', index, message: String(e && e.message || e) });
                return;
            }
            self.postMessage({ type: 'ready', index, gpu: adapterLabel });
            return;
        }
        case 'config':
            applyConfig(msg.args);
            writeParams();
            return;
        case 'track':
            applyConfig(msg.config);
            buildAndUploadTrack(msg.def);
            return;
        case 'pop': {
            popStart = msg.start; popN = msg.count; hidden = msg.hidden;
            ex.pop_init(popN, popStart, hidden, msg.seed);
            if (msg.focused) i32v(ex.car_focused_ptr(), popN).set(msg.focused.subarray(0, popN));
            focusLo = msg.focusLo === undefined ? -1 : msg.focusLo;
            focusHi = msg.focusHi === undefined ? -1 : msg.focusHi;
            ex.set_focus_window(focusLo, focusHi);
            ex.pop_reset();
            lastBrains = msg.brains.slice(0, popN * ex.brain_stride());
            uploadPopulation(lastBrains, packFromWasm(), popN, null, msg.lanes);
            return;
        }
        case 'reset':
            ex.pop_reset();
            uploadPopulation(lastBrains, packFromWasm(), popN, null, lanes);
            return;
        case 'import': {
            popStart = msg.start; popN = msg.count; hidden = msg.hidden;
            ex.pop_init(popN, popStart, hidden, msg.seed);
            focusLo = msg.focusLo === undefined ? -1 : msg.focusLo;
            focusHi = msg.focusHi === undefined ? -1 : msg.focusHi;
            ex.set_focus_window(focusLo, focusHi);
            // Mirror the imported cars into wasm too, so a later 'reset'
            // (which rebuilds the start state there) keeps their focus flags.
            new Uint32Array(memory.buffer, ex.state_ptr(), popN * STATE_WORDS).set(msg.state);
            ex.unpack_state();
            lastBrains = msg.brains.slice(0, popN * ex.brain_stride());
            uploadPopulation(lastBrains, msg.state, aliveIn(msg.state), msg.gateRatio || null, msg.lanes);
            return;
        }
        case 'run':
            await run(msg);
            return;
        case 'export': {
            const state = mirror.slice();
            const crashCount = crashMirror.slice();
            const gateRatio = popStart === 0 ? gateMirror.slice() : null;
            const transfer = [state.buffer, crashCount.buffer];
            if (gateRatio) transfer.push(gateRatio.buffer);
            self.postMessage({ type: 'exported', index, start: popStart, count: popN, state, crashCount, gateRatio }, transfer);
            return;
        }
    }
}

// The current slice's brains, kept host-side so a 'reset' (which re-uploads
// the whole start-of-run population) doesn't need them sent again.
let lastBrains = new Float32Array(0);

// Strictly one message at a time. 'run' awaits the GPU, and without this a
// 'config' or 'pop' arriving meanwhile would interleave with it — the CPU
// worker gets this ordering for free by being synchronous.
let queue = Promise.resolve();
self.onmessage = e => {
    const msg = e.data;
    queue = queue.then(() => handle(msg)).catch(err => {
        const message = String(err && err.message || err);
        if (msg.type === 'init') self.postMessage({ type: 'gpu-error', index, message });
        else { console.error('gpu-worker:', err); if (!lost) { lost = true; self.postMessage({ type: 'gpu-lost', index, message }); } }
    });
};
